### ISSUE TITLE
isotrop.py should use neighbours2 version of Hensel's notation

### ISSUE THREAD

**Issue by apaap** [dvgrn/b3s23life#1]
It seems confusing to have this version of the rule generator here, when it is not compatible with Golly and Lifeviewer. Did you mean to include this one or the version you posted to the forum here http://conwaylife.com/forums/viewtopic.php?p=27226#p27226

**Comment by dvgrn** [comment]
Thanks for pointing this out.  For some reason I thought that Eric Goldstein's script had gotten updated to match Alan Hensel's neighbors2 table.
